### ISSUE TITLE
Ctrl+Space don't work

### ISSUE THREAD

**Issue by TheKeiki** [rostok/ubichr#10]
As the title says, I can't launch the app with the ctrl+space command, I try in both my laptop and pc (fresh install of chrome) with the extension pinned and unpinned from the bar and nothing happend, did I miss anything?

**Comment by rostok** [comment]
Yes, I am aware of the issue yet don't know the reason for this. The simple workaround is to set the keyboard shortcut manually in the browser. To do so go to chrome://extensions/shortcuts and press pencil icon on the UbiChr row and then press Ctrl+Space.

**Comment by TheKeiki** [comment]
Yep, that makes the trick, thanks a lot, I really liked it a lot  back in the original ubiquity and to be able to use it now is mind blowing.

**Comment by rostok** [comment]
As the issue seems solved I will close it. I also found some solutions that total reinstall (full uninstall and install again) of the extension should set the shortcuts, but cant confirm it ATM. 

Very glad you found it useful. I longed the original Ubiquity so much I decided to recreate it by myself for Chrome.
